### ISSUE TITLE
Adding Continent Code to JSON Response

### ISSUE THREAD

**Issue by obihill** [fiorix/freegeoip#101]
Thanks for this great GEOIP Platform.

I'm looking for a way to add `continent_code` to the list of geo variables. How can I do this?

Thanks.

**Comment by fiorix** [comment]
You have to add continent to the maxmind query in https://github.com/fiorix/freegeoip/blob/master/encoder.go#L162. See the maxminddb package documentation for details.

**Comment by obihill** [comment]
Thanks a lot. Sorry for troubling you but I'm not familiar with the go language. Could please advise the additions I need to make to your code to get it to work?

**Comment by fiorix** [comment]
Like I said you'll have to read the maxminddb's documentation to understand their query model and add those fields to the struct in the link above. I thought about adding that and other data available in the db in the last version, but couldn't because of backwards compatibility of the csv endpoint of the API. You'll need a programmer to make those changes for you.

**Comment by anarchoi** [comment]
GeoPlugin supports country code easily. I wanted to switch to FreeGeoIP but my app needs country code :(
