### ISSUE TITLE
Feature: local time/date value

### ISSUE THREAD

**Issue by Fironet** [fiorix/freegeoip#107]
Was looking for a way to return the local time and date from an IP query. Being able to check the local time/date would be super useful and complement the existing time zone value. Hopefully such a feature makes its way into a new release, as the project continues to be great.

**Comment by fiorix** [comment]
This is actually easier said than done. A few years back I had a database with the time offset of all time zones, but it turns out these don't get updated too often and become very inaccurate. The start and end of daylight saving in some countries don't follow any logic and are more tied to politics. That makes it really hard to keep up with the changes. That was the main reason this feature was removed.

**Comment by fiorix** [comment]
More info here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones

Will close this for now but consider a revamp of this feature for the future.

**Comment by oschwald** [comment]
Go's `time` package supports the IANA Time Zone database, which should simplify this a bit. If you don't want to rely on the system version of this, you can download the latest from [IANA](http://www.iana.org/time-zones).

**Comment by fiorix** [comment]
Mmmm, you're right. This http://golang.org/pkg/time/#ParseInLocation is probably the key to this problem given that I find a way to keep the database up to date. Reopening.

**Comment by fiorix** [comment]
Or this http://golang.org/pkg/time/#Time.In, probably even better.

**Comment by fiorix** [comment]
So, this is similar to what I experienced in the past: http://brokenbad.com/281/
Governments decide to change DST at will for random reasons and all of a sudden services like mine become inaccurate.

**Comment by fiorix** [comment]
Since the current code returns the timezone name, I'm closing this ticket and have no plans to return the timezone's local time for now.
