### ISSUE TITLE
Is freegeoip again under a heavy load or DDoS attack?

### ISSUE THREAD

**Issue by jared83** [fiorix/freegeoip#150]
Right now it is unacceptably slow. I mean like the slowest service I have ever used.
I know it is free, but even then...
Do issues like this happen often?
I can put up with once a year or a quarter of a year or so, but any more often than that and the service becomes useless.
Maybe you could upgrade your infrastructure, and / or charge a little for a better service?
Could be worthwhile, considering how popular this service is and how much commercial products of this nature cost.
cheers
Jared

**Comment by fiorix** [comment]
Hey @jared83 it's frustrating to both of us. For the past 3-4 months I've been getting panics on 1 or 2 out of the 4 servers at least twice a day. You're experiencing slowness probably because you're hitting one of these servers that was dead (http://i.imgur.com/PSdz7lm.png) but still a valid dns entry.

Since this is a hobby/side project, I don't have a lot of time to put on the infrastructure and haven't really done much over the summer, although I'm aware of the situation. This past weekend I've experimented with a temporary, bigger cluster for ipv6 traffic and things went well, and I'm currently writing some patches to the server software to deploy a new infrastructure in the next few days. Gotta find something that fits my budget.

This is why if you look back into the previous tickets I've been telling people to download the freegeoip server software and deploy in their own infrastructure for the desired SLA, and I honestly think production servers shouldn't rely on some random public/free service like mine. At any rate, changes will come soon and hopefully resolve the stability problem.

**Comment by rodolfobandeira** [comment]
I don't understand why people complains about a free service if you are sharing the whole project to anyone install it and use in their own infrastructure.

**Comment by williamsjj** [comment]
Have to agree with @rodolfobandeira, if you're running a production service you should run your own. That's what we did. Its obviously very convenient to use the free service, but it takes an hour to get it set up including automation with Chef or the like (https://github.com/williamsjj/chef-freegeoip). 

That being said, given how often this comes up maybe @fiorix is overlooking an opportunity to charge for a paid service. :) We started with the free and depending on the price I'm not sure if we wouldn't have bought a paid plan to continue using a reliable service given we didn't need to do anything special.

**Comment by fiorix** [comment]
New cluster is up and running since last night. Much better latency so far, monitoring in place, etc... let's see how long it lasts before DDoS hit it badly.

**Comment by jared83** [comment]
I understand what you are saying, but bear in mind that many of us do not have the infrastructure you speak of. I'm a front-end dev who caters for clients who usually use third parties for hosting that do not let you have any access to their infrastructure. Having my own VPS is not an option either at the moment. This is the market segment who usually use services like freegeoip - it is quick and easy and when it works it does so splendidly. 
@fiorix thanks for your work. For now it is blazing fast. Kudos to you man!

**Comment by fiorix** [comment]
No problem. All the tunings are paying off: http://i.imgur.com/2Oz3Gvk.png

**Comment by lenovouser** [comment]
@fiorix Awesome! Could you tell be what you are using to monitor the `req's` or what the name of the dashboard in the screenshot is?

**Comment by fiorix** [comment]
The freegeoip code (https://github.com/fiorix/freegeoip/tree/master/apiserver) is now instrumented to collect stats for https://prometheus.io and the dashboard in the screenshot is PromDash.

**Comment by fiorix** [comment]
here's an update: http://imgur.com/a/LY3CK
