### ISSUE TITLE
Wrong Location & IP

### ISSUE THREAD

**Issue by ayoub-bousetta** [fiorix/freegeoip#199]
the Website & API recently started to show wrong locations & IP address comparing to other alternatives show my exacte location/ip.... 

Any help would be appreciated

**Comment by Levak** [comment]
Hi,

If I understand the OP correctly, I have the same issue.
Since very recently, going to https://freegeoip.net/json will not give you your public IP anymore, but a totally different one.

I used to ping https://freegeoip.net/json to get my public IP, much like "whatismyip" sites. Is it an intended behavior?

Thanks,

**Comment by lenovouser** [comment]
Yep, same here. Actual IP differs from the IP displayed

**Comment by ayoub-bousetta** [comment]
@Levak Exactly what i'm talking about... i tried a lot of websites "alternatives" they return the same IP (my exact location) unlike freegeoip

**Comment by omercnet** [comment]
I think the issue is with the xff headers, the IP it's returning belongs to cloudflare

in the meantime you guys are welcome to use my clone at https://ip.omer.io/json

**Comment by ayoub-bousetta** [comment]
@omercnet Perfect, thank you...

**Comment by fiorix** [comment]
Hey thanks for this @omercnet! I haven't been very responsive here due to limited access to internet but last night I emailed Rich which is currently looking after the servers to enable the use of xff headers again.

The problem here is that CloudFlare has been bypassing our traffic for the past couple years due to high volume thus we disabled xff. Now they're proxying again and we need to enable it. From what I hear Rich has already enabled xff but there seems to be issues because cf isn't proxying all traffic so we're vulnerable to clients faking xff to bypass our quota system.

I'm working with him to mitigate/fix this asap. Things should go back to normal next week for me. In the mean time I suggest once more that you download the freegeoip web server and run your own instances, as usual ;)

**Comment by omercnet** [comment]
@fiorix do you know why it's not proxying all the traffic?
You could easily add in authenticated origin requests with a CF cert so you can only allow traffic from CF on your end and block anything else
I'd be happy to help with the configuration if you need

**Comment by omercnet** [comment]
I migrated the server to a dedicated host, feel free to use it as an alternative mirror https://geoipfree.com

**Comment by ayoub-bousetta** [comment]
@omercnet Thank you so much for your help...

**Comment by fiorix** [comment]
@omercnet I don't know the details and honestly haven't looked at it yet. Will do at some point next week when I have internet at home again. I might ping you offline in case I need help. Please drop me an email so we can talk there. Thanks!

**Comment by omercnet** [comment]
@fiorix emailed your gmail

**Comment by alvincosio** [comment]
hey guys, can you help me to fix my weather widget. suddenly it gave a wrong location. my geolocation used https://freegeoip.net.

**Comment by fiorix** [comment]
@alvincosio there's no much we can do here. The database is downloaded automatically from MaxMind, so your best bet is submit corrections to them.

**Comment by SiyabongaNzulwana** [comment]
Hi guys, I am also getting the same problem, freegeoip is returning this
```
{data: {…}, status: 200, statusText: "OK", headers: {…}, config: {…}, …}
config
:
{adapter: ƒ, transformRequest: {…}, transformResponse: {…}, timeout: 0, xsrfCookieName: "XSRF-TOKEN", …}
data
:
city
:
""
country_code
:
""
country_name
:
""
ip
:
"172.17.0.1"
latitude
:
0
longitude
:
0
metro_code
:
0
region_code
:
""
region_name
:
""
time_zone
:
""
zip_code
:
""
__proto__
:
Object
headers
:
{content-type: "application/json"}
request
:
XMLHttpRequest {onreadystatechange: ƒ, readyState: 4, timeout: 0, withCredentials: false, upload: XMLHttpRequestUpload, …}
status
:
200
statusText
:
"OK"
```

and this is how I am making the call 
```
 const browserData = await axios.get('http://localhost:8080/json/')
    console.log("browserData ", browserData)
```
