### ISSUE TITLE
SSL certificate expired on freegeoip.net

### ISSUE THREAD

**Issue by maximbaz** [fiorix/freegeoip#216]
![image](https://cloud.githubusercontent.com/assets/1177900/24177432/bea98d0c-0ea2-11e7-9f78-1f8ecbc6c9ff.png)

**Comment by packetrich** [comment]
That was my fault.  I had to go out of town for work and thought I'd be back in time to make the update, but I got tied up with something and ran late. I bought a 3-year cert so we should be good for the foreseeable future, and as of  March 21 @ 23:00 (UTC-4) the servers are running on the new cert. 

@fiorix you can close this out.

**Comment by omercnet** [comment]
@packetrich please consider switching to letsencrypt

**Comment by mundomatt** [comment]
@maximbaz Still experiencing the same issue as you. If the certs were installed on a per server basis maybe one of the servers didn't get the updated cert?

**Comment by maximbaz** [comment]
Good to know that it's not me alone who experiences this issue then...

The example above does indeed show that servers use two different certificates. Both of them were acquired on March 22, one of them expires in March 2020, while another expires in September 2017. And interestingly enough, only the one that expires in 2020 causes all the trouble.

**Comment by Plasma** [comment]
Was getting a few server related errors (server unavailable, Origin Connection Time-out) a few hours ago too.

**Comment by mrdefenestrator** [comment]
I'm also experiencing the same problem as @maximbaz.  It appears there is 4 IPs for freegeoip.net, 2 for cloudflare, 2 elsewhere.  The two cloudflare IPs (with the Sept 2017 expiring SSL certs) work fine, the others do not.  SSL Labs flags the chain configuration on the servers that are giving me problems: https://www.ssllabs.com/ssltest/analyze.html?d=freegeoip.net&s=158.69.243.235

**Comment by maximbaz** [comment]
This error seems to be fixed for me somehow:

```
❯  curl --insecure -v https://freegeoip.net/json/ 2>&1 | awk 'BEGIN { cert=0 } /^\* Server certificate:/ { cert=1 } /^\*/ { if (cert) print }'
* Server certificate:
*  subject: OU=Domain Control Validated; OU=PositiveSSL Multi-Domain; CN=sni48214.cloudflaressl.com
*  start date: Mar 22 00:00:00 2017 GMT
*  expire date: Sep 28 23:59:59 2017 GMT <---------------
*  issuer: C=GB; ST=Greater Manchester; L=Salford; O=COMODO CA Limited; CN=COMODO ECC Domain Validation Secure Server CA 2
*  SSL certificate verify ok. <---------------
* Connection #0 to host freegeoip.net left intact

❯  curl --insecure -v https://freegeoip.net/json/ 2>&1 | awk 'BEGIN { cert=0 } /^\* Server certificate:/ { cert=1 } /^\*/ { if (cert) print }'
* Server certificate:
*  subject: OU=Domain Control Validated; OU=PositiveSSL; CN=freegeoip.net
*  start date: Mar 22 00:00:00 2017 GMT
*  expire date: Mar 21 23:59:59 2020 GMT <---------------
*  issuer: C=GB; ST=Greater Manchester; L=Salford; O=COMODO CA Limited; CN=COMODO RSA Domain Validation Secure Server CA
*  SSL certificate verify ok. <---------------
* Connection #0 to host freegeoip.net left intact
```

**Comment by packetrich** [comment]
I think I have it resolved on the server side. I had a bad file copy when I was moving things around last night across the servers and it broke the cert chain for my cert. It may help to give an overview of what things look like on my side.

So I control 3 of the IPv4 servers: (don't hard code the IPs since I rotated in and out about a dozen servers over the last year due to capacity and/or hardware issues/failures)
A - 158.69.242.138
B - 158.69.243.235
C - 198.27.81.74
If you check the bottom left corner of the web page render you can see the server letter and freegeoip version I run. That is is how I keep track of where I am when trying to troubleshoot.

I was a fan of the project and heard @fiorix was going to shut down the original service back in February/March 2016, so I offered to host the servers myself out of my own pocket as my donation. @fiorix  wanted to get out of the care and feeding of infrastructure, and I really just wanted to stay quietly in the background and help keep things running. There have been some growing pains.... as I started off with 2 much smaller servers and I worked to try to size for capacity built in for the "right size". Over the summer I was DoS'd off the map by a fairly large corporation that slammed the API millions of times in 15 minute increments multiple times a day. Now I think I have the proper size and quantity of physical servers, so the service runs as you see today.... which hopefully works for the most part.

@fiorix still holds the DNS and CloudFlare for the domain name and I have no control over that. There may be other servers out there, but I don't know... I just tell him which servers I want to rotate in and which ones I rotate out, and he fixes the DNS on my behalf. The 3/22/17 - 3/22/20 is my certificate and that is on my servers. For the one from 3/22/17 to 9/28/17 that one is done by CloudFlare and from what I hear from @fiorix it's auto-generated by ClouidFlare just like letsencrypt. I attempted letsencrypt for the SSL automation (less maintenance for me), but with me not knowing which server will get hit for the DNS validation and they all share the freegeoip.net name, I'd need to do some scripting to make it sync across what I have, but in a hurry last night (and not wanting to spin up a test server in the middle of crunch time), I purchased a new cert and went with the static SSL certs I already am familiar with until I can get time to see how I can use letsencrypt with the given setup.

Probably more than anyone ever wanted to know, but that is the way it has mostly worked in the background for the past year. I'd like to thank @fiorix for the assistance/support/knowledge he has given me and letting me keep things running on his behalf.

**Comment by maximbaz** [comment]
Thanks @packetrich for keeping this wonderful service alive!

**Comment by maximbaz** [comment]
@mundomatt, @mrdefenestrator do you confirm that the issue is resolved for you too? It's working all right for me, so I'm OK with closing it.

**Comment by mrdefenestrator** [comment]
Seconding the thanks to @packetrich!

@maximbaz looks like things are consistently working on my end.
