### ISSUE TITLE
Request: include IP ranges in response

### ISSUE THREAD

**Issue by daumling** [fiorix/freegeoip#236]
I dunno if your databases deliver this info, but in order to e.g. track IPs, it would be beneficial to have the IP address range for the block that the IP is allocated to. Very often, ISPs switches IP addresses every night for DSL connections, and this would make it far easier to assign these IPs correctly. For the same reason, the provider's AS number would be helpful. Currently, a call to the RIPE REST APIs provide this info, but it would be great to have this info gathered with a single call.

**Comment by fiorix** [comment]
IP ranges aren't possible with the current fb as far as I know. We also discussed having ASN in the past but the discussion ended up nowhere.

I have no plans to support this myself because managing another db with download and synchronisation for AS is out of scope for me. If you're willing to give it a shot I'd be happy to review the code but no promise it'll be merged.
